using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Goobstation.Client.DoomArcade;

[GenerateTypedNameReferences]
public sealed partial class DoomArcadeMenu : DefaultWindow
{
    private DoomArcadeControl _gameControl;

    public DoomArcadeMenu()
    {
        RobustXamlLoader.Load(this);

        _gameControl = new DoomArcadeControl();
        _gameControl.HorizontalExpand = true;
        _gameControl.VerticalExpand = true;
        GameContainer.AddChild(_gameControl);
    }

    public int GetScore() => _gameControl.Game.Score;
    public DoomArcadeControl GameControl => _gameControl;

    public void UpdateLabels()
    {
        var game = _gameControl.Game;
        ScoreLabel.Text = $"SCORE: {game.Score}";
        HpLabel.Text = $"HP: {game.PlayerHp}";
        AmmoLabel.Text = $"AMMO: {game.PlayerAmmo}";
    }
}
